### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by Severse** [loiste-interactive/infra-issues#1188]
I decided to make a linux port of INFRA after reading [this](https://steamcommunity.com/app/251110/discussions/0/458606248630816213/) steam community page. It has been going good so far but, I am stuck at the moment. Whenever I run this command to launch INFRA:
`LD_LIBRARY_PATH=~/.steam/bin32/ ~/.steam/bin32/steam-runtime/run.sh ./infra.sh -game infra`
I get this error:
`Can't find background image 'materials/console/portal2_product_2.vtf' and
 Can't find background image 'materials/console/portal2_product_2.vtf'
`
I am quite confused and have tried multiple ways of fixing this. Do you have any idea why this is happening? Before this wasn't happening but then suddenly appeared after changing nothing. Maybe it might be something to do with me borrowing some files from the portal 2 folder.

Thanks, Severse

**Comment by Severse** [comment]
I figured out how to get past this error and will continue experimenting till I get INFRA to run on linux. Thank you!

**Comment by CorruptComputer** [comment]
Huh, I don't think that'll work as they have an edited version of the engine, and if you just copy the .so (Linux version of .dll) libraries it'll probably mess up pretty badly. Also it's a completely different engine version to begin with so there's bound to be more issues there too. Best of luck though, I am curious on how this turns out!
