### ISSUE TITLE
Crash when dying if a demo is being recorded

### ISSUE THREAD

**Issue by FireWarp** [loiste-interactive/infra-issues#124]
1.Start recording a demo.
2.Touch a death trigger.
Instant crash
100% reproducible
EDIT: Crashes even if I stop recording

**Comment by sebastiannielsen** [comment]
I suppose this is unfixable and is related to the heavy usage of the source engine so theres no "room" for the demo system.
So a quick'n'dirty fix would be to soft-disable demo recording alltogheter, and those that want to record a demo and know it gonna crash at dying, can still continue on their own risk.

Like a error message:
>record "test"
<"Demo recording is intentionally disabled due to crash issues when dying. If you still want to continue on your own risk, use /force".
>record "test" /force
(starts recording a demo).

**Comment by aleksijuvani** [comment]
It might be possible to fix this, but I don't think it's really worth the time investment. Not many people use the feature. Besides, demos are really broken at the moment, so this isn't the only thing that would have to be fixed.

I've completely disabled demo recording in the next update.

**Comment by aleksijuvani** [comment]
Looks like there are some people out there that actually used the feature, so I'm going to look into fixing this in the future.

**Comment by aleksijuvani** [comment]
I've fixed the crash, but there are still some other issues with demos that I'll need to address.

**Comment by aleksijuvani** [comment]
All the major issues are fixed in 1.1.4.
