### ISSUE TITLE
Global feedback and suggestions

### ISSUE THREAD

**Issue by ontrigger** [loiste-interactive/infra-issues#143]
Alright, here we go. Let's start from the first map.

Reserve1: 
1)Intro scene is bad, does not provide any kind of backstory or info about the game. It's a big problem because I had no idea that I could just run through the game without solving any puzzles. Just put it clear to a player that you can do whatever you want in the game by displaying a text on a black screen.

2)Now let's take a look at these 2 areas:
![2015-11-07_00013](https://cloud.githubusercontent.com/assets/8556074/11016226/9f57aafc-858b-11e5-8096-d48f0e8c460c.jpg)
![2015-11-07_00014](https://cloud.githubusercontent.com/assets/8556074/11016227/a4e6967c-858b-11e5-831f-cd553b4be937.jpg)
They are very dark, right? What they clearly need is some dim lighting to highlight the small details and add to the overall atmosphere. A constant light with a soft falloff and a green-ish tint will do the trick. I will explain why flashlight is not needed here a little bit later.
![2015-11-07_00015](https://cloud.githubusercontent.com/assets/8556074/11016330/f3c3bfc4-858e-11e5-8ddc-fe99ed014b2d.jpg)

3)In this picture you can see a damaged pillar, but unlike any other pillar that is clearly visible this one is obscured by a tree behind me. It is almost impossible to notice even if you turn around to the right after turning on a water flow monitor. Will be better if you remove that tree.

4)Well, if I stated a water flow monitor then why not to talk about it too?
I seriously have no idea what these things do and what their purpose is, can anybody explain that to me?

5)Alright, so now we enter the power plant and here we are greeted with the first puzzle in the game. This is a great opportunity to teach your player about the basic mechanics of the game. Tell a player how the camera works and what we he/she should do with it. 
![2015-11-07_00016](https://cloud.githubusercontent.com/assets/8556074/11016342/8e67fc8e-858f-11e5-971d-e2bf8b8a609b.jpg)
I personally think that this cutter blends with the box way too much thus rendering it literally invisible. I was lucky enough to notice it and pick it up. I think it would be better to make this section have no lighting at all. Not only that it fits perfectly well with the broken fuses, but it encourages our player to use the flashlight. Put the cutter somewhere so it doesn't blend with its surroundings and put a light switch near it to reward a player for finding the cutter(cutter here is a visual cue to help find a light switch, although that will mean that some players will try to use light switches further in the game).

6)The paper on a table in the same power plant should be more readable. You can achieve that by putting it higher and adjusting tonemap scale so that lightmaps don't overbrighten certain letters.  

7)I was kind of confused with what I was supposed to do with a console in that plant. Did I have to turn them both off or just one?

Reserve2:
1)I have a lot of critique for this map.
![2015-11-07_00018](https://cloud.githubusercontent.com/assets/8556074/11016411/b832c060-8591-11e5-97aa-0b6bc13a0ecd.jpg)
First of all, the lighting HAS to be changed for this area. It is very moody and dark. Sudden contrasts on bright lights make it look even worse. I couldn't distinguish a static prop with physics one not only because their textures were almost identical, but also because it was too dark to see the difference(blue-ish tone didn't help). I suggest making this room way more brighter with a soft yellow-ish tone. Physics props should be stacked at one place and probably somehow highlighted(maybe make a small storage room with a cagelight?)
same thing can be applied to the splicer generator room, lighting is just meh.
![2015-11-07_00019](https://cloud.githubusercontent.com/assets/8556074/11016451/2facbc80-8593-11e5-9587-349ec5fe2ece.jpg)

2)We are now in a sawmill, a very dark sawmill. Seriously, how come there are 4 lights along the wall with brigh as fuck sprites yet the sawmill is super dark. 
![2015-11-07_00021](https://cloud.githubusercontent.com/assets/8556074/11016469/8bd84074-8593-11e5-80f3-549ee0231728.jpg)

3)The death trigger for the small motor should be much smaller and should actually fit its size. It also has some incorrect timing because it kills you even if the motor is all the way down the basement.

3)I actually have to say that I liked the electrical water puzzle here, on my first playthrough I tried to put a bunch of boxes there, now I feel like a stupid idiot because the powerbox had a small timer so that I could just turn it on and run away before it electrifies everything.
![2015-11-07_00024](https://cloud.githubusercontent.com/assets/8556074/11016516/f1fcf92a-8594-11e5-8227-c3b7471957d7.jpg)
![2015-11-07_00022](https://cloud.githubusercontent.com/assets/8556074/11016517/f42156b0-8594-11e5-8def-6cf85c1d02a6.jpg)

4)These stands should have a map telling you where exactly you are right now. I didn't even know that you could go to the claw point.

Reserve3: 
This one is perfectly executed except for one serious issue. You cannot close the toilet after throwing a poop where it belongs. Things like that really bug me.

I'm kind of tired of writing this but I'll post feedback for all levels later so don't close this issue, thanks.

**Comment by FireWarp** [comment]
Forgot to mention some interesting stuff:
Some grass textures are way brighter than they should be. Turn on mat_fullbright and fly around reserve maps, it is really noticeable. All foliage should have the same color, right now it looks very unnatural.
![2015-11-05_00002](https://cloud.githubusercontent.com/assets/8556074/11016576/7481d2a6-8597-11e5-86bc-8c19df0ba706.jpg)

Put a skybox instead of an areaportal right here, It should gradually increase performance

**Comment by FireWarp** [comment]
Tunnel:

I enjoyed this level on my first playthrough quite a lot, mostly because of fascinating puzzles, only to realise on my second playthrough that there are some serious design flaws:

First and the foremost, there are 2 puzzles in this level, the one that I solved on my first playthrough was a two way bridge. I felt smart about it and completely forgot about the second one, which I thought was some kind of a secret. Turns out it was not. The second puzzle is just a different way to complete a level. I was kinda dissapointed, but that wasn't really the bad part. The bad part was that if the first puzzle rewarded me with a cool backstory of this place(like the table with cards and a look at the huge tunnel), the second one did not reward me with anything at all. I feel bad for those who took the water sensors route

On the theme of secrets, I kept thinking that I had clearly missed something. This was not true, in fact, the devs themselves missed like half the sounds for this level as almost every single door did not have any sound effects.

Finally, here goes an elevator that brings me to the level transition. TBH it feels super lame and scripted. There was no sign at all that it would crash(no visual or sound cue), you just touch a trigger and it falls down super fast. You can get stuck in that elevator just like in my reserve1 video, i think this is possible with every single elevator in the game.
 
Totally forgot, those lights with full white glowing sprites still look very unnatural. They should be filling the whole place with light, for now they are just sprites that look cool in water reflections.

**Comment by FireWarp** [comment]
More feedback for reserve maps
You certainly need more rock models. Those that you have right now look low res and have these green spots on them making them look repetitive in the distance. I see this rock with a hole in it everywhere 
![2015-11-08_00003](https://cloud.githubusercontent.com/assets/8556074/11020760/28c5e9b6-863b-11e5-9247-197e2cb401ce.jpg)
This cliff right here is made completely out of them. Sculpt some more models, make huge complex ones for different areas that have baked lighting in them (so that you can still have bumpmaps and support bumpmapping at the same time)

**Comment by FireWarp** [comment]
Tunnel2:
This map should be changed from the ground up. Let's see what's wrong. 

![2015-11-07_00003](https://cloud.githubusercontent.com/assets/8556074/11020812/3cce16b6-863d-11e5-829a-11b75afe03e8.jpg)
The window in the left corner had such a short field of view that It was almost impossible to notice this pipe entrance.
![2015-11-07_00004](https://cloud.githubusercontent.com/assets/8556074/11020849/9e29807a-863e-11e5-96dc-8d87bf427bb1.jpg)
Now, I'm a very big fan of showing players where they are supposed to go right from the start of a level. It at least gives some kind of a starting point to help build a logical chain of things that a player has to do to finish a level. On my first playthrough I did not give any significance to both the metal door and the window as I thought they were not connected at all. Because of this I had no idea how to finish this level. 

![2015-11-07_00006](https://cloud.githubusercontent.com/assets/8556074/11021117/1284b822-8649-11e5-981f-a70560476073.jpg)
Then I visited this room. The paper telling me to close the pipes then the pumps confused me a little. That was because I noticed beforehand that the railings there were colored red and blue just like the pipes.  The model for these buttons should be changed completely to fit the artstyle of the level and tell the player that these buttons are not related to pipes at all and represent a different part of the level.

Then I visited the control room and saw the scheme on a computer. There was an additional line for each pipe color. I opened the turquosite line though I had no idea what it did and why I had to do it.
I started looking out for those additional pipes but never found them. I "closed" the blue pipe, something went wrong and in the end I had no idea if the pipe was closed or opened.  I had to return to the control room several times just to check if what I was doing was correct. After running around for a while I decided to map the scheme onto the layout of the level and got completely lost.
![2015-11-08_00004](https://cloud.githubusercontent.com/assets/8556074/11021307/897ab21a-864e-11e5-9fe4-2b3dba7ce3e5.jpg)
I noticed that these pipes lead to nowhere and also that they are inverted. 
I then closed all pumps (turns out that I actually opened them) went to the control room again, ran around  the facility, somehow I fixed my problem with pumps by actually closing them this time, opened the gate and finished the map.

**Comment by FireWarp** [comment]
I also forgot about the button room and the lost key. On my second playthrough I realised that these buttons were nothing but a way to get a key and get to the next level. Just like with tunnel1, this was just an another way to finish the map. In fact, the second solution is not even a solution since you can already escape this map and all you have to do to get the key and escape is just an addition to the first solution. I thought that I would get something interesting, maybe some kind of a story piece that i couldn't have gotten if I finished this level by entering a pipe. Well, yeah, I got nothing.

Alright, so my suggestions on how to improve this level. 
1)
![movewindow](https://cloud.githubusercontent.com/assets/8556074/11021423/db973520-8651-11e5-933c-df50b8de5a89.png)
Move this window where I show it in the picture. Then move the pipe entrance right where the wooden door was so that the point of interest is this pipe(and so that players can see it through the window clearly). Then contrast this pipe put a bright red light indicating you cant enter it or something.

2)
![2015-11-07_00005](https://cloud.githubusercontent.com/assets/8556074/11021445/75809dca-8652-11e5-805c-4613acc98cdd.jpg)
Move this control room here
![movethecontrolroom](https://cloud.githubusercontent.com/assets/8556074/11021469/00984ca0-8653-11e5-90b2-36a69b610523.png)
Now I can clearly see the pipes. 
3) Add these 2 computer controlled pipes. No idea where you can place them but if the controll room is moved to the front then you will have to do some refurnishing in the building. It would also be cool if you could make these cpu pipes visible from the control room. The scheme should also be remapped to correctly show how pipes and pumps correlate in the facility. And please change the water pool icon to be more readable. I had no idea what it meant.

Add sound effects for the pipes to indicate water flowing through them, again , I had to check multiple times if water was flowing on the computer. I think pump mechanic should be changed, instead of closing the pumps turn them on or off.

Finally, the biggest problem is the solutions themselves. The key to the tunnel is not needed at all, it just adds a few more steps to finish the level, plus it doesn't reward the player with anything and that is something you should definately change.

Finally

**Comment by FireWarp** [comment]
I've made some edits to my 2 previous posts, check them out. I've also been thinking on an improved layout for the level, if you think my additions could work tell me right now and I will post my version of the layout

**Comment by FireWarp** [comment]
Tunnel3:
The raft ride is bad:
* Not rewarding
* Heavy variance in deaths and therefore frustration because of different skill levels, for example I died 3 times at the beginning and did very consistently throughout caves(total 5 deaths)
* Requires a lot of concentration
* Player has no clue when to turn unless already died at that area
* Not enough time to relax after a tough part
* Not sure when to relax
* **Not fun**

How to make it fun?

**_Raft movement should be controlled by triggers/cpu 80% of the time_**
* Adjust strafe speed, position and rotation when needed (Reduces huge differentiation in death counts, optimal death count should be 2-3 and increase only on tough parts)
  * Fast strafes in tunnel, slower strafes in caves
  * Adjust strafe time when a player is about to crash into something(do it only if it is a near miss)
  * Trigger a feature above only in very hard parts of a level
  * (Help players)Adjust position and rotation of a raft so they can safely take photos/relax

**_Players are able to rotate the raft by standing on a corner_**
*  If raft hits a boulder with a bottom corner(usually these are behind the player) play a sound resembling a hit.
* Help players rotate by adjusting rotate speed when needed

**_Dynamic raft destruction (Helps building tension if some part split off; Players at the end will likely have their rafts look almost completely destroyed  This will make them think that they were close to death thus feel very good)_** 
* If raft hits a boulder once, split off the part that got hit.
* At the end make rafts bottom part completely collapse so that the front barely floats
* Built-in flashlight should go off at some point so all you have left is your own(The farther you go the harder it gets)

**_Make slight changes to caves and the tunnel itself_**
* Sharp 30-80 degree sharp/smooth turns to add variety(going forward is boring + auto adjusting mechanic should slightly help)
* Problem: Players will have no idea where the water is flowing because it is very dark
 * Add particles indicating that water is hitting a certain rock very hard(gives a sense of the direction, helps players prematurely know when to turn)
 * Illuminate the area better, adjust scrolling speed
 * Add some debris flowing on the water in brightly lit areas(p2 engine allows that) to distract players(helps fix players concentrating too much)
* Change elevation - movement speed of the raft to add extra challenge
* Make built in flashlight go off on tunnel4:
 * To account battery problems, create battery islands as shown in this visually appealing picture
![lolo](https://cloud.githubusercontent.com/assets/8556074/11037517/3857ba38-870f-11e5-89d3-70cf2b285ace.png)

**Comment by FireWarp** [comment]
So here's a summary:
* Add an auto turning/correcting mechanic to help players control the raft
* Add more variety to challenges in the tunnel(sharp turns, i.e)
* Gradually extend the tunnel and all of its sections(that is because it is going to be slightly easier with new mechanics)
* Increase the speed the farther we are away from start (to make it more challenging and less boring)
* Make the raft dynamically destructible 
* Make it possible to rotate the raft(rotate speed also controlled by relays)

**Comment by Oskutin** [comment]
Toiled should be fixed now :D

**Comment by FireWarp** [comment]
What about everything else?

**Comment by Oskutin** [comment]
Some have already been fixed by some degree and taking feedbacks into account. Some still need some work.
