### ISSUE TITLE
Graphical problems and confusing puzzle

### ISSUE THREAD

**Issue by DevinShadowV** [loiste-interactive/infra-issues#174]
In Reserve 2 and Tunnel 1...
![1](https://cloud.githubusercontent.com/assets/15645339/11167624/3f009b7a-8b1f-11e5-88ee-b4d4e529a9f8.jpg)
![2](https://cloud.githubusercontent.com/assets/15645339/11167623/3f007f78-8b1f-11e5-9c8a-f6ab6eb21208.jpg)
![3](https://cloud.githubusercontent.com/assets/15645339/11167625/3f01af60-8b1f-11e5-8675-62ee30ea8d94.jpg)
![4](https://cloud.githubusercontent.com/assets/15645339/11167626/3f020eec-8b1f-11e5-97f5-18539cb223c9.jpg)

**Comment by aleksijuvani** [comment]
Hey, thanks for the feedback.

> ![1](https://cloud.githubusercontent.com/assets/15645339/11167624/3f009b7a-8b1f-11e5-88ee-b4d4e529a9f8.jpg)

I'm creating a separate issue to track this one.

> ![2](https://cloud.githubusercontent.com/assets/15645339/11167623/3f007f78-8b1f-11e5-9c8a-f6ab6eb21208.jpg)

This is an issue with the glow particles, tracked in #46.

> ![3](https://cloud.githubusercontent.com/assets/15645339/11167625/3f01af60-8b1f-11e5-8675-62ee30ea8d94.jpg)

This is a bug with use highlights, tracked in #58.

> ![4](https://cloud.githubusercontent.com/assets/15645339/11167626/3f020eec-8b1f-11e5-97f5-18539cb223c9.jpg)

You can grab those smaller wooden crates and toss them to create a safe path through the water. I know it's kind of confusing right now because they don't have use highlights.
