### ISSUE TITLE
sewer: Multiple problems

### ISSUE THREAD

**Issue by JerkyNero** [loiste-interactive/infra-issues#224]
There should be a checkpoint here after passing the fire obstacle:
![2015-12-20_00002](https://cloud.githubusercontent.com/assets/2118899/11920771/75c91bf4-a72c-11e5-9fff-e5aeb30560ad.jpg)

And here, after exiting the building to the catwalk:
![2015-12-20_00003](https://cloud.githubusercontent.com/assets/2118899/11920784/9086ab14-a72c-11e5-8bba-3af50e830696.jpg)

And lastly, here, after navigating the forklift obstacle:
![2015-12-20_00006](https://cloud.githubusercontent.com/assets/2118899/11920786/a64ce6ac-a72c-11e5-9209-9cb470837700.jpg)

I think collision should be applied to the garage door even if you lift it all the way up with the forklift:
![2015-12-20_00004](https://cloud.githubusercontent.com/assets/2118899/11920791/c44d47dc-a72c-11e5-921d-b2298954f7d5.jpg)

I had to keep reverting to my last checkpoint because I kept breaking this:
![2015-12-20_00007](https://cloud.githubusercontent.com/assets/2118899/11920799/ce4e5bcc-a72c-11e5-82cb-3698837dd5a9.jpg)
Why can't I reset it? The power switch doesn't work once I turn it on.

I got stuck here when taking a photograph.
![2015-12-20_00005](https://cloud.githubusercontent.com/assets/2118899/11920808/f7f85c48-a72c-11e5-8865-acf0e4551fcb.jpg)

I though that this ladder would work, but it didn't... maybe you could split it in half or move it to somewhere inaccessible?
![2015-12-20_00001](https://cloud.githubusercontent.com/assets/2118899/11920818/1783b828-a72d-11e5-92c2-e937ce27f368.jpg)

**Comment by N-G-Neer** [comment]
I made the same comment about the puzzle not reseting. It's intentional, hence all the warnings painted on the machine. This is not mandatory to progress though.

**Comment by JerkyNero** [comment]
How does it affect the game then? I realize that it turns on the pump in the canal, but is it important? I took a picture of it, but nothing happened.

**Comment by Zuntti** [comment]
Added checkpoints, fixed photograph place, ladder is split in half and mushroom machine puzzle is now easier.

**Comment by N-G-Neer** [comment]
> How does it affect the game then? I realize that it turns on the pump in the canal, but is it important? I took a picture of it, but nothing happened.

This is what is called a "spot repaired" puzzle. I assume it will have some bearing on the game ending but it has no direct effect on the level itself. Here, people were protesting because of the horrible stench coming from the canal. I assume turning on the pump wlll eventually sort that problem. Like the pumping station in tunnel2. You can either cut the water for a good chunk of Stalburg so you can take the easy route down the main pipe or you can run around for several more minutes, turn back the chlorination tank and repair the whole station, then continue through the collapsed staircase. It won't affect you but other people in Stalburg.
