### ISSUE TITLE
Reserve 1 graphical problems and a question

### ISSUE THREAD

**Issue by DevinShadowV** [loiste-interactive/infra-issues#225]
I'll have the screen caps pointing out the problems with the usual plants and trees parts are missing in the distance until I get close up but this is more standing out. At release are we going to have a manual save feature and don't have to rely on auto checkpoints? Plus are we going to have a developer console feature at launch as well?

![1](https://cloud.githubusercontent.com/assets/15645339/11949480/7fcb7f1c-a834-11e5-8c83-b17e1e182d11.jpg)
![2](https://cloud.githubusercontent.com/assets/15645339/11949482/7fce61aa-a834-11e5-9fb4-3beaf7aea574.jpg)
![3](https://cloud.githubusercontent.com/assets/15645339/11949481/7fce0084-a834-11e5-84d9-22edb6b9e3c3.jpg)
![4](https://cloud.githubusercontent.com/assets/15645339/11949484/7fcfef48-a834-11e5-87c1-99ef2b925b5b.jpg)
![5](https://cloud.githubusercontent.com/assets/15645339/11949483/7fce828e-a834-11e5-8c4e-11e461889e8a.jpg)

**Comment by aleksijuvani** [comment]
> ![1](https://cloud.githubusercontent.com/assets/15645339/11949480/7fcb7f1c-a834-11e5-8c83-b17e1e182d11.jpg)
![2](https://cloud.githubusercontent.com/assets/15645339/11949482/7fce61aa-a834-11e5-9fb4-3beaf7aea574.jpg)

The car has been textured in the next update.

> At release are we going to have a manual save feature and don't have to rely on auto checkpoints?

Yes, the final release will have manual saves. Saves are disabled (well, not disabled, just hidden) in the beta as they are not backwards compatible. This shouldn't be a huge issue since all maps are available to play from the main menu.

> Plus are we going to have a developer console feature at launch as well?

It will continue to be available via launch options.

> ![5](https://cloud.githubusercontent.com/assets/15645339/11949483/7fce828e-a834-11e5-8c4e-11e461889e8a.jpg)

This looks like an issue with area portals. It can happen if you noclip past triggers, but should never happen if you just walk around in the map. What route did you take? Or did this happen after noclipping?

**Comment by DevinShadowV** [comment]
I went the long way not going across the river but walking on the wooden bridge, pass the train tracks, right through the house and passed the WWII bomb and then hang a right and it triggered. But this morning I went the short route mean I went across the river on the make shift pulley raft and saw the route and it didn't trigger.

**Comment by Oskutin** [comment]
That areaportal problem should now be fixed. Found one place where you can bypass the areaportal opening trigger, which is walking beyhind the red house.

**Comment by Oskutin** [comment]
That electrical box is also fixed.
