### ISSUE TITLE
Camera battery should drain primarily when taking pictures

### ISSUE THREAD

**Issue by lordcrc** [loiste-interactive/infra-issues#323]
I think that the camera battery should drain primarily when taking pictures, and not when simply viewing through the display.

I know that IRL the display does consume a fair bit of energy, but it just seems a bit silly to have to micro-manage such a thing to such an extent.

I got almost 2x as many pictures if I brought up camera, took picture as soon as possible and then packed away the camera as quickly as possible, compared to waiting a few seconds before and after taking a picture.

**Comment by CorruptComputer** [comment]
I also think the battery lives of the camera and flashlight should be extended, because they are extremely short.

**Comment by aleksijuvani** [comment]
I've decreased the power consumption of the camera screen from 0.5% per second to 0.33% per second in the next update.

I think the flashlight is fine. It's meant to be used sparingly and there are plenty of batteries for it. I did a playthrough where i had over ten batteries left over.

I suppose we could increase its battery life and decrease the amount of batteries though, but that's something that requires a bit more thought.

**Comment by lordcrc** [comment]
Thanks, I look forward to the update.

Personally I was fine with the flashlight. Though I guess it depends heavily on the player's environment, since the game lacks gamma controls. 

I play in a room which I can make pick black, so I only needed it for a few areas. If you play in a living room when the sun is up, I can imagine that you'd have to use the flashlight more often.

**Comment by aleksijuvani** [comment]
That's a good point.

**Comment by sebastiannielsen** [comment]
One suggestion could be to replace the camera batteries with SD cards instead, eg the camera will always have enough power for the whole workday (since most cameras do have hours of play), but you have limited number of pictures due to the lack of memory in camera. A good camera along with cheap memory cards (because the city council does not have much money to spare) would not give so much pictures per card. A good 16MP camera today takes pictures of about 4-5 MB, and a 64MB card would give about 10-15 pictures.
Also, the camera could be replaced with a smartphone, almost none today have cameras nowadays.
http://steamcommunity.com/app/251110/discussions/0/458606877326042655/
