### ISSUE TITLE
Things are too bright

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#475]
Near the train switch: 
![2016-02-06_00001](https://cloud.githubusercontent.com/assets/5573038/12868632/f8076d28-cccf-11e5-8313-2c742290caa6.jpg)
https://youtu.be/KGHvVLmTHUw

At the power station before sawmill: 
![2016-02-06_00004](https://cloud.githubusercontent.com/assets/5573038/12868636/068e1928-ccd0-11e5-802c-881b5da2c0a9.jpg)
![2016-02-06_00005](https://cloud.githubusercontent.com/assets/5573038/12868637/068f1cf6-ccd0-11e5-8d0d-2d22b3b6926c.jpg)

**Comment by sebastiannielsen** [comment]
Can you explain more? What are too bright? The first pic shows a hill that are alighted by sun, thus it will provide reflection and of course the effect shown.
Second the same, since that part of the hill has a flatter profile, the sun will reach the hill and cause it to light up more.

The third is the only I could understand, the left part of the fence looks brighter than the right.Might be a texture issue than a lighting issue.

**Comment by CorruptComputer** [comment]
In the first pic the shadow extends beyond that rock, therefor it shouldn't be that bright. In the second pic if you look closely (hard to get a pic of) it was really bright in the corner, when it shouldn't have been.

**Comment by Yuccaa** [comment]
Lighting errors in the last two images fixed. Some things like that bright corner can't really be fixed though.

**Comment by Yuccaa** [comment]
Fixed.
