### ISSUE TITLE
Compilation of Bugs/Issues/Complaints

### ISSUE THREAD

**Issue by JerkyNero** [loiste-interactive/infra-issues#86]
reserve1
![2015-11-01_00001](https://cloud.githubusercontent.com/assets/2118899/10901108/f6719722-819d-11e5-8f3e-4e2767a78211.jpg)
I feel like the truck should be on a flat level, or have the ground where the player gets out be lower. It was disorienting at first. Plus, you can see the tires sinking into the ground.

Saw this at the barn house:
![2015-11-01_00004](https://cloud.githubusercontent.com/assets/2118899/10901125/54f4b81a-819e-11e5-9274-6f12c9636f15.jpg)

Not the best texture in the world:
![2015-11-01_00005](https://cloud.githubusercontent.com/assets/2118899/10901134/73d07080-819e-11e5-9663-fc51b0336a65.jpg)

As cute as this little Outhouse is, it's in the chapter 3 times. If it didn't have a heart carved in the door, then it'd be fine.
![2015-11-01_00007](https://cloud.githubusercontent.com/assets/2118899/10901140/90a52ae8-819e-11e5-9cc9-413a51246e5c.jpg)

When attempting to traverse through the flooded control room in the dam, I noticed that you could see the sparking generators through the walls.
![2015-11-01_00009](https://cloud.githubusercontent.com/assets/2118899/10901205/8e46bcde-819f-11e5-8507-e0e2ccb0a574.jpg)
![2015-11-01_00010](https://cloud.githubusercontent.com/assets/2118899/10901206/91329ff8-819f-11e5-82c2-cac9d78739e3.jpg)

It's a bit hard to see, but you can see tiny white dots in the bottom left corner on the first picture.

reserve2
After I activated Hartman's recording in the control room, I went outside to realize it was still playing, and it was echoing throughout the whole valley. The sound should be played in the room only, not on the player in my opinion.

I got stuck here at the elevator
![2015-11-01_00013](https://cloud.githubusercontent.com/assets/2118899/10901260/4ff2607c-81a0-11e5-9d42-4104b5aaebaf.jpg)
![2015-11-01_00014](https://cloud.githubusercontent.com/assets/2118899/10901261/52c4c07e-81a0-11e5-91da-b3d52885b75b.jpg)

This wasn't highlighted when hovering over it.
![2015-11-01_00020](https://cloud.githubusercontent.com/assets/2118899/10901325/11aebfb2-81a1-11e5-918f-7e8eecb6439b.jpg)

tunnel2
Missing texture:
![2015-11-01_00011](https://cloud.githubusercontent.com/assets/2118899/10901432/0dc93c22-81a3-11e5-8e98-13a7e1190e99.jpg)

tunnel3
I really detest this map. I don't like the boat ride at all. I died around thirty times trying to control the damn thing. I feel that the boat was also too sensitive, especially since the current wasn't that fast. I felt like kissing the ground once I got off that thing!
There are also some points where if you crash your boat, you can get off onto piles of rubble rather than dying, but you won't get far anyway.
Also (and I'm not sure if you guys just haven't put the sound in yet or not), if the water was moving the boat, I think there should've been a looping sound for the water since it's moving.
tower
I had to skip this map entirely because my game kept crashing. Every time I'd go to the top of tower and activate all buttons, I'd get a buffer error, my frame rate would drop and I'd crash. I lowered all my video settings to see if that was the problem, but it wasn't. I played this around five times just to be sure.

UPDATE: After the current update, I still can't play after activating the fuses. Keeps crashing.

Other issues:
The pause menu.
![2015-11-01_00006](https://cloud.githubusercontent.com/assets/2118899/10901165/e02f5aa2-819e-11e5-9bd0-68583c4cb1b8.jpg)
Players should be able to access Options and also be able to Load and Save their game. I've started a few levels over at least several times after getting quite far because I got stuck somewhere.
I think this is EXTREMELY important.
I also think the screen should fade out a little to indicate the game is paused rather than just have the options show up, because looking at my screen from afar, I couldn't tell if my game was paused or not.

Flashlight vs. Camera
I didn't like having to use batteries for both the flashlight and camera. While I realize this is realistic, it also was very challenging because I didn't know at first that the camera actually had a battery life; I thought only the flashlight did. But why I don't like it is because I took pictures of everything I thought was a flaw in the architecture of the building, only to realize it was just texturing and not an actual problem (like mold or markings on the walls). Then my camera died, I was out of batteries, and I had to pass debris that I knew was a problem until I could find some more.

**Comment by aleksijuvani** [comment]
Hey, thanks for the feedback! Sorry for taking this long to respond – for some reason this didn't show up on the list at all unless I sorted by recently updated.

> I also think the screen should fade out a little to indicate the game is paused rather than just have the options show up, because looking at my screen from afar, I couldn't tell if my game was paused or not.

I agree. I'm going to take a look at this once I update the pause menu.

> Flashlight vs. Camera
I didn't like having to use batteries for both the flashlight and camera. While I realize this is realistic, it also was very challenging because I didn't know at first that the camera actually had a battery life; I thought only the flashlight did. But why I don't like it is because I took pictures of everything I thought was a flaw in the architecture of the building, only to realize it was just texturing and not an actual problem (like mold or markings on the walls). Then my camera died, I was out of batteries, and I had to pass debris that I knew was a problem until I could find some more.

I feel like the game isn't doing a very good job at explaining the mechanics to the player. I hope that some tutorial messages will improve the situation.

> tower
I had to skip this map entirely because my game kept crashing. Every time I'd go to the top of tower and activate all buttons, I'd get a buffer error, my frame rate would drop and I'd crash. I lowered all my video settings to see if that was the problem, but it wasn't. I played this around five times just to be sure.

This should be fixed in the next update. See issue #95.

> tunnel3
I really detest this map. I don't like the boat ride at all. I died around thirty times trying to control the damn thing. I feel that the boat was also too sensitive, especially since the current wasn't that fast. I felt like kissing the ground once I got off that thing!

I think that the main problem here is that you can't clearly perceive where the edges of the raft are. Adding some more light here could improve things. It might also be cool to make the raft sustain at least one hit before falling apart.

> There are also some points where if you crash your boat, you can get off onto piles of rubble rather than dying, but you won't get far anyway.

Yeah, this is kind of stupid. Needs to be fixed.

> Also (and I'm not sure if you guys just haven't put the sound in yet or not), if the water was moving the boat, I think there should've been a looping sound for the water since it's moving.

I agree.

> When attempting to traverse through the flooded control room in the dam, I noticed that you could see the sparking generators through the walls.

This issue is tracked in #46.

> Players should be able to access Options and also be able to Load and Save their game. I've started a few levels over at least several times after getting quite far because I got stuck somewhere.
I think this is EXTREMELY important.

I agree. This is kind of shit right now. The options menu issue is tracked in #16.

> tunnel2
Missing texture

This issue is tracked in #33.

**Comment by Oskutin** [comment]
The tower thing should be finally fixed in the next update.
