### ISSUE TITLE
cistern: player can block pallet truck by standing on it

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#863]
![20161030123940_1](https://cloud.githubusercontent.com/assets/3168386/19836037/11c5d966-9e9e-11e6-8470-089fa50cac55.jpg)

This whole thing still feels really finicky. I feel like it should be replaced by the button that these gate models usually have when they can be opened from the other side.

**Comment by sebastiannielsen** [comment]
No, because actually, you are exiting the construction area. Note that you are entering INSIDE the construction area, with the truct and shed, while "outside" of the gate (the barrel side), all/most construction elements are elevated except for a few. So it would not make sense to have a button on the gate, instead these barrels just happen to be placed there.

If it needs to be replaced, I would suggest something else placed there, maybe a "electrical bear" ( construction electrical supply, like these:)
 ![Elbjörn](http://www.stavdal.se/assets/images/resized/assets/images/uploads/product-images/239_elbjorn_u32_200x200_s.jpg)

that can be moved by the player by pressing "use" (just a slide to the left would make sense, and a playerclip can prevent player entry into the movement space).

**Comment by aleksijuvani** [comment]
Replacing the barrels with another moveable obstacle wouldn't solve anything. As you said, the barrels just happen to be placed there. They can easily be moved. The gate is unlocked, so anyone could enter the area from that side anyway.

The issue with the barrels is mostly that people don't realize they can interact with them (plus they're really finicky right now). A button would be obvious and consistent.

Besides, the upper section on this side does the button thing with its gate anyway:

![20161103145229_1](https://cloud.githubusercontent.com/assets/3168386/19966824/27afdb74-a1d6-11e6-8bcd-98e8819ae65b.jpg)

To solve the issue that you described, we could use keys here instead, but that poses another issue. Where would the keys be located? What if the player misses them? They would have to be in a very obvious place to allow backtracking. I feel like this is more trouble than it's worth.

**Comment by Yuccaa** [comment]
Replaced with button.
